from app import app, db, Course

courses = [
    # VISUAL COURSES
    Course(title='Introduction to Programming (Video Series)', description='A complete video course covering programming basics with animations and visual examples perfect for beginners.', subject='Computer Science', level='100 Level', resource_link='https://www.youtube.com/watch?v=zOjov-2OZ0E', course_type='Visual'),
    Course(title='Data Structures Visualized', description='Learn data structures through beautiful animations and visual diagrams that make complex topics easy to understand.', subject='Computer Science', level='200 Level', resource_link='https://visualgo.net', course_type='Visual'),
    Course(title='Mathematics for Engineers (Video Lectures)', description='Video based mathematics course covering calculus, algebra and statistics with visual explanations for engineering students.', subject='Mathematics', level='100 Level', resource_link='https://www.khanacademy.org/math', course_type='Visual'),
    Course(title='Circuit Analysis Video Tutorials', description='Step by step video tutorials on electrical circuit analysis with visual diagrams and animations for engineering students.', subject='Electrical Engineering', level='200 Level', resource_link='https://www.youtube.com/watch?v=mc979OhitAg', course_type='Visual'),
    Course(title='Human Anatomy Video Series', description='Detailed video lectures on human anatomy with 3D visualizations and diagrams for medical and nursing students.', subject='Medicine', level='200 Level', resource_link='https://www.khanacademy.org/science/health-and-medicine', course_type='Visual'),
    Course(title='Business Management Video Course', description='Comprehensive video lectures on business management principles, organizational behaviour and leadership for Nigerian students.', subject='Business Administration', level='200 Level', resource_link='https://www.coursera.org/learn/wharton-business-foundations', course_type='Visual'),
    Course(title='Geography of Nigeria Video Lectures', description='Comprehensive video lectures covering physical and human geography of Nigeria including landforms, climate and natural resources.', subject='Geography', level='100 Level', resource_link='https://www.youtube.com/watch?v=7RMxGCU1GhQ', course_type='Visual'),
    Course(title='Physics Video Lectures for Beginners', description='Engaging video lectures covering fundamental physics concepts including mechanics, waves and electricity with visual demonstrations.', subject='Physics', level='100 Level', resource_link='https://www.khanacademy.org/science/physics', course_type='Visual'),
    Course(title='Chemistry Video Tutorials', description='Comprehensive video tutorials covering organic and inorganic chemistry with visual molecular diagrams and laboratory demonstrations.', subject='Chemistry', level='100 Level', resource_link='https://www.khanacademy.org/science/chemistry', course_type='Visual'),
    Course(title='Architecture Design Video Course', description='Visual video course covering architectural design principles, building structures and urban planning for architecture students.', subject='Architecture', level='200 Level', resource_link='https://www.youtube.com/watch?v=Jrq7RQWVZMQ', course_type='Visual'),
    Course(title='Mechanical Engineering Video Lectures', description='Comprehensive video lectures covering mechanical engineering principles including thermodynamics and fluid mechanics with visual diagrams.', subject='Mechanical Engineering', level='200 Level', resource_link='https://www.youtube.com/watch?v=SFW4oiHMSq0', course_type='Visual'),
    Course(title='Economics Video Lectures', description='Engaging video lectures covering micro and macroeconomics principles and Nigerian economic policies with visual charts and graphs.', subject='Economics', level='200 Level', resource_link='https://www.khanacademy.org/economics-finance-domain', course_type='Visual'),
    Course(title='Statistics and Data Visualization Course', description='Comprehensive video course covering statistics, data analysis and visualization techniques with graphs and charts for university students.', subject='Mathematics', level='300 Level', resource_link='https://www.khanacademy.org/math/statistics-probability', course_type='Visual'),
    Course(title='Accounting and Finance Video Course', description='Comprehensive video lectures covering accounting principles, financial statements and financial management for accounting students.', subject='Accounting', level='100 Level', resource_link='https://www.youtube.com/watch?v=yYX4bvQSqbo', course_type='Visual'),
    Course(title='Nursing Care Video Tutorials', description='Detailed video tutorials covering nursing care procedures, patient management and clinical skills for Nigerian nursing students.', subject='Nursing', level='200 Level', resource_link='https://www.youtube.com/watch?v=eBzMByybBg0', course_type='Visual'),

    # READING COURSES
    Course(title='Introduction to Computer Science (MIT Notes)', description='Comprehensive written lecture notes from MIT covering all fundamental Computer Science concepts for university students.', subject='Computer Science', level='100 Level', resource_link='https://ocw.mit.edu/courses/6-0001-introduction-to-computer-science-and-programming-in-python-fall-2016/', course_type='Reading'),
    Course(title='Business Law and Ethics Textbook', description='A complete reading resource covering Nigerian business law, corporate governance and professional ethics for business students.', subject='Business Administration', level='300 Level', resource_link='https://openstax.org/books/business-law-i-essentials/pages/1-introduction', course_type='Reading'),
    Course(title='Engineering Mathematics Textbook', description='Free online textbook covering all engineering mathematics topics with detailed written explanations and examples for Nigerian students.', subject='Mathematics', level='200 Level', resource_link='https://openstax.org/subjects/math', course_type='Reading'),
    Course(title='Principles of Economics (Written Course)', description='Detailed written course covering micro and macroeconomics principles relevant to the Nigerian economy and business environment.', subject='Economics', level='100 Level', resource_link='https://openstax.org/books/principles-economics-3e/pages/1-introduction', course_type='Reading'),
    Course(title='Introduction to Law (Reading Materials)', description='Comprehensive reading materials covering Nigerian law, legal systems and constitutional law for law students.', subject='Law', level='100 Level', resource_link='https://www.lawteacher.net/free-law-essays/introduction-to-law/', course_type='Reading'),
    Course(title='Introduction to Microbiology Study Notes', description='Detailed written study notes covering microbiology concepts, bacteria, viruses and laboratory techniques for science students.', subject='Microbiology', level='300 Level', resource_link='https://www.ncbi.nlm.nih.gov/books/NBK7627/', course_type='Reading'),
    Course(title='Geography of Africa Study Notes', description='Detailed written study notes covering the geography of Africa including physical features, climate zones and economic resources.', subject='Geography', level='200 Level', resource_link='https://www.nationalgeographic.org/encyclopedia/africa/', course_type='Reading'),
    Course(title='Introduction to Mass Communication (Study Guide)', description='Comprehensive reading materials covering mass communication theories, media ethics and journalism in the Nigerian context.', subject='Mass Communication', level='200 Level', resource_link='https://www.open.edu/openlearn/society-politics-law/media-studies/content-section-0', course_type='Reading'),
    Course(title='Introduction to Agriculture (Study Materials)', description='Comprehensive reading materials covering crop production, soil science and agricultural economics relevant to Nigerian farming.', subject='Agriculture', level='100 Level', resource_link='https://www.fao.org/home/en/', course_type='Reading'),
    Course(title='Introduction to Pharmacy (Study Notes)', description='Detailed written study notes covering pharmacology, drug interactions and pharmaceutical chemistry for Nigerian pharmacy students.', subject='Pharmacy', level='300 Level', resource_link='https://www.pharmpress.com/free-resources', course_type='Reading'),
    Course(title='Introduction to Education (Study Guide)', description='Comprehensive reading materials covering educational psychology, teaching methods and curriculum development for Nigerian education students.', subject='Education', level='100 Level', resource_link='https://www.open.edu/openlearn/education-development/education/content-section-0', course_type='Reading'),
    Course(title='Introduction to Physics (Study Notes)', description='Detailed written study notes covering fundamental physics concepts including mechanics, thermodynamics and electricity for university students.', subject='Physics', level='100 Level', resource_link='https://openstax.org/books/university-physics-volume-1/pages/1-introduction', course_type='Reading'),
    Course(title='Mechanical Engineering Textbook', description='Comprehensive written textbook covering mechanical engineering fundamentals including thermodynamics and fluid mechanics for Nigerian students.', subject='Mechanical Engineering', level='300 Level', resource_link='https://openstax.org/subjects/science', course_type='Reading'),

    # PRACTICAL COURSES
    Course(title='Python Programming Projects for Beginners', description='Hands on Python programming course where you build real projects from day one perfect for practical learners in Computer Science.', subject='Computer Science', level='200 Level', resource_link='https://www.freecodecamp.org/learn/scientific-computing-with-python/', course_type='Practical'),
    Course(title='Web Development Bootcamp (Hands-on)', description='Build real websites from scratch using HTML, CSS and JavaScript through practical hands on exercises for Nigerian university students.', subject='Computer Science', level='300 Level', resource_link='https://www.freecodecamp.org/learn/responsive-web-design/', course_type='Practical'),
    Course(title='Accounting Practice Exercises', description='Practical accounting exercises covering bookkeeping, financial statements and Nigerian tax calculations for accounting students.', subject='Accounting', level='200 Level', resource_link='https://www.accountingcoach.com/accounting-basics/quiz', course_type='Practical'),
    Course(title='Civil Engineering Lab Projects', description='Practical civil engineering projects and experiments covering structural analysis and material testing for Nigerian engineering students.', subject='Civil Engineering', level='300 Level', resource_link='https://www.engineeringintro.com', course_type='Practical'),
    Course(title='Business Plan Development Workshop', description='Practical workshop where you develop a real business plan step by step relevant to the Nigerian market and business environment.', subject='Business Administration', level='300 Level', resource_link='https://www.sba.gov/business-guide/plan-your-business/write-your-business-plan', course_type='Practical'),
    Course(title='GIS and Mapping Practical Course', description='Hands on practical course on Geographic Information Systems and digital mapping techniques used in modern geography and urban planning.', subject='Geography', level='300 Level', resource_link='https://www.esri.com/training/catalog/search/', course_type='Practical'),
    Course(title='Medical Clinical Practice Guide', description='Practical clinical skills guide for medical students covering patient examination, diagnosis and treatment procedures in Nigerian hospitals.', subject='Medicine', level='400 Level', resource_link='https://www.amboss.com', course_type='Practical'),
    Course(title='Electrical Engineering Circuit Lab', description='Hands on electrical engineering laboratory exercises covering circuit design, testing and troubleshooting for Nigerian engineering students.', subject='Electrical Engineering', level='300 Level', resource_link='https://www.tinkercad.com/circuits', course_type='Practical'),
    Course(title='Economics Data Analysis Workshop', description='Practical workshop covering economic data analysis, research methods and statistical tools relevant to Nigerian economic studies.', subject='Economics', level='300 Level', resource_link='https://www.worldbank.org/en/research', course_type='Practical'),
    Course(title='Chemistry Laboratory Experiments', description='Hands on chemistry laboratory experiments covering titration, chemical reactions and analysis techniques for Nigerian science students.', subject='Chemistry', level='200 Level', resource_link='https://www.labxchange.org', course_type='Practical'),
    Course(title='Agriculture Field Practice Guide', description='Hands on practical guide covering crop planting, soil testing, irrigation techniques and farm management for Nigerian agriculture students.', subject='Agriculture', level='200 Level', resource_link='https://www.agrifarming.in', course_type='Practical'),
    Course(title='Law Moot Court Practice', description='Practical guide for law students covering courtroom procedures, legal arguments and case studies relevant to Nigerian law.', subject='Law', level='300 Level', resource_link='https://www.lawteacher.net/free-law-essays/', course_type='Practical'),
    Course(title='Teaching Practice Workshop', description='Hands on teaching practice workshop covering lesson planning, classroom management and assessment techniques for Nigerian education students.', subject='Education', level='300 Level', resource_link='https://www.teachervision.com', course_type='Practical'),
    Course(title='Microbiology Laboratory Practical Guide', description='Hands on laboratory practical guide covering microscopy, culture techniques and microbial analysis for Nigerian science students.', subject='Microbiology', level='300 Level', resource_link='https://www.microbiologyonline.org', course_type='Practical'),
    Course(title='Mass Communication Media Production', description='Hands on media production workshop covering radio broadcasting, television production and digital journalism for Nigerian students.', subject='Mass Communication', level='300 Level', resource_link='https://www.coursera.org/learn/journalism', course_type='Practical'),
    Course(title='Architecture Design Studio Project', description='Hands on architecture design studio project covering building design, structural planning and construction techniques for Nigerian students.', subject='Architecture', level='300 Level', resource_link='https://www.archdaily.com', course_type='Practical'),
]

with app.app_context():
    existing_titles = [c.title for c in Course.query.all()]
    added = 0
    for course in courses:
        if course.title not in existing_titles:
            db.session.add(course)
            added += 1
    db.session.commit()
    print(f'Added {added} new courses! Total now: {Course.query.count()}')